name: Build PR Documentation

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_documentation:
    runs-on: ubuntu-22.04
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.number }}
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
      PR_CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache-dependency-path: "kit/package-lock.json"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup environment
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/huggingface/doc-builder
          pip install .[quality] accelerate

      - name: Make documentation
        shell: bash
        run: |
          doc-builder build optimum docs/source/ \
            --repo_name optimum-onnx \
            --build_dir onnx-doc-build/ \
            --version pr_${{ env.PR_NUMBER }} \
            --version_tag_suffix "" \
            --html \
            --clean
          cd onnx-doc-build
          mv optimum optimum-onnx
          echo ${{ env.COMMIT_SHA }} > ./commit_sha
          echo ${{ env.PR_NUMBER }} > ./pr_number

      - uses: actions/upload-artifact@v4
        with:
          name: doc-build-artifact
          path: onnx-doc-build/