name: Exporters ONNX / Python - Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  UV_SYSTEM_PYTHON: true
  UV_TORCH_BACKEND: auto
  TRANSFORMERS_IS_CI: true
  HF_HUB_READ_TOKEN: ${{ secrets.HF_HUB_READ_TOKEN }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        runs-on: [ubuntu-22.04]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip uv
          uv pip install .[tests,onnxruntime] diffusers

      - name: Test with pytest
        run: |
          pytest tests/exporters/onnx/test_export.py -vvvv -n auto
